/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "FaWatchDogServer_constants.h"

namespace faWatchDogServer {

const FaWatchDogServerConstants g_FaWatchDogServer_constants;

FaWatchDogServerConstants::FaWatchDogServerConstants() {
}

} // namespace

