/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FaWatchDogServer_CONSTANTS_H
#define FaWatchDogServer_CONSTANTS_H

#include "FaWatchDogServer_types.h"

namespace faWatchDogServer {

class FaWatchDogServerConstants {
 public:
  FaWatchDogServerConstants();

};

extern const FaWatchDogServerConstants g_FaWatchDogServer_constants;

} // namespace

#endif
